name: weather_wizard
description: "A new Flutter project for the know a weather."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

#  design
  cupertino_icons: ^1.0.6
#  flutter_staggered_grid_view: ^0.7.0

  iphone_has_notch: ^1.0.0
  timer_count_down: ^2.2.2
  cached_network_image: ^3.4.0
  intl: ^0.19.0
  shimmer: ^3.0.0
  lottie: ^3.1.2
  flutter_screenutil: ^5.9.3
  keyboard_dismisser: ^3.0.0
  device_preview: ^1.2.0
  l: ^4.0.2
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.14
  pinput: ^5.0.0



#  state management
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  get_it: ^8.0.2
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4

# network
  dio: ^5.7.0
  connectivity_plus: ^6.0.0


# locale
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.0.0

#  routing
  go_router: ^14.6.0

#  location
  geolocator: ^8.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.11



flutter_intl:
  enabled: true

flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/image/
    - assets/svg/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
